# Generated by Django 5.1.3 on 2024-11-20 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('question', models.TextField(blank=True, null=True)),
                ('asnwer', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(blank=True, default=False, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_client', to='user_profile.clientprofilemodel')),
            ],
            options={
                'db_table': 'faq_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(blank=True, default=False, null=True)),
                ('appointment_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_anonymous', models.BooleanField(blank=True, default=False, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_review', to='user_profile.clientprofilemodel')),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_review', to='user_profile.counselorprofilemodel')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-created_at'],
            },
        ),
    ]
