# Generated by Django 5.1.3 on 2024-11-20 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment_management', '0002_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProgress',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('status', models.CharField(blank=True, choices=[('ASSIGNED', 'assigned'), ('ONGOING', 'ongoing'), ('COMPLETED', 'completed'), ('INCOMPLETE', 'incomplete')], default='ASSIGNED', max_length=100, null=True)),
                ('session_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_progress_client', to='user_profile.clientprofilemodel')),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_progress_counselor', to='user_profile.counselorprofilemodel')),
            ],
            options={
                'db_table': 'client_progress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProgressDetails',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('details', models.TextField(blank=True, null=True)),
                ('progress_date', models.DateField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_appointment', to='appointment_management.appointmentrequest')),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_details', to='user_profile.clientprofilemodel')),
            ],
            options={
                'db_table': 'client_progress_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
