# Generated by Django 5.1.3 on 2024-11-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselorresource',
            name='status',
        ),
        migrations.AddField(
            model_name='counselorresource',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherresource',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
