# Generated by Django 5.1.3 on 2024-11-24 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('ASSIGNED', 'assigned'), ('COMPLETED', 'completed'), ('CANCELLED', 'cancelled')], default='ASSIGNED', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AppointmentRequestCancel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('details', models.TextField(blank=True, null=True)),
                ('emergency_document', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=100, null=True)),
                ('is_refund', models.BooleanField(blank=True, default=False, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_cancel_request', to='appointment_management.appointmentrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_cancel_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_request_cancel',
                'ordering': ['-created_at'],
            },
        ),
    ]
